# Generated by Django 4.2 on 2023-05-24 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ManyToManyField(to='mainapp.category'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='subcategory',
            field=models.ManyToManyField(to='mainapp.subcategory'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.ManyToManyField(to='mainapp.type'),
        ),
    ]
