# Generated by Django 4.2 on 2023-05-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_medicine_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.PositiveIntegerField(),
        ),
    ]
