# Generated by Django 4.2 on 2023-05-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_medicine_img_medicineimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='medicine'),
        ),
        migrations.DeleteModel(
            name='MedicineImage',
        ),
    ]
