# Generated by Django 4.2 on 2023-05-25 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medicine_images')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.medicine')),
            ],
        ),
    ]
