# Generated by Django 4.2 on 2023-05-25 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_medicineimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineImage',
        ),
    ]
