# Generated by Django 4.2 on 2023-05-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_medicine_quantity_alter_medicine_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
