# Generated by Django 4.2 on 2023-05-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_cartitem_myuser_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='cart_items',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
